---

- name: "Install LEMP Stack with PHP 5.6, Nginx + ngx_cache_purge and MySQL on Ubuntu 14.04"
  hosts: all
  sudo: yes
  roles:
    - { role: common, tags: ['common'] }
    - { role: timezone, tags: ['timezone'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: ufw, tags: ['ufw'] }
    - { role: unattended-upgrades, tags: ['unattended-upgrades'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: mysql, tags: ['mysql'] }
    - { role: postfix, tags: ['postfix'] }
    - { role: php, tags: ['php'] }
    - { role: composer, tags: ['composer'] }
    - { role: wp-cli, tags: ['wp-cli'] }
    - { role: dropbox-uploader, tags: ['dropbox-uploader'] }
