---

- name: "Install LEMP Stack with PHP 5.6, Nginx + ngx_cache_purge and MySQL on Ubuntu 14.04"
  hosts: all
  sudo: yes
  roles:
  - common
  - timezone
  - ssh
  - unattended-upgrades
  - capistrano-setup
  - nginx
  - mysql
  - php
  - composer
  - wp-cli
  - vhost-wordpress
