---

- name: Create MySQL database
  mysql_db:
    name: "{{ item.name }}"
    state: present
  with_items: mysql_databases
  when: item.name|default(False)

- name: Create MySQL user
  mysql_user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    priv: "{{ item.name }}.*:ALL"
    state: present
  with_items: mysql_databases
  when: item.user|default(False) and item.user|default(False) and item.name|default(False)

- name: Copy database dump
  copy:
    src: "{{ item.import }}"
    dest: /tmp
  with_items: mysql_databases
  when: item.import|default(False)

- name: Import database
  mysql_db:
    name: "{{ item.name }}"
    state: import
    target: "/tmp/{{ item.import | basename }}"
  with_items: mysql_databases
  when: item.import|default(False)

- name: Delete database dump on remote
  file:
    path: "/tmp/{{ item.import | basename }}"
    state: absent
  with_items: mysql_databases
  when: item.import|default(False)
