---

- name: MySQL | Create database
  mysql_db:
    name: "{{ item.mysql_database }}"
    state: present
  with_items: vhosts
  when: item.use_mysql == true
  tags: [vhost]

- name: MySQL | Create DB user
  mysql_user:
    name: "{{ item.mysql_username }}"
    password: "{{ item.mysql_password }}"
    priv: "{{ item.mysql_database }}.*:ALL"
    state: present
  with_items: vhosts
  when: item.use_mysql == true
  tags: [vhost]
