---

- name: nginx | Create vhost's directory
  file:
    path: "/srv/www/{{ item.domain }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: vhosts
  tags: [vhost]

- name: nginx | Create public_html directory
  file:
    path: "/srv/www/{{ item.domain }}/public_html"
    state: directory
    owner: "{{ item.deploy_username | default('deploy') }}"
    group: "{{ item.deploy_username | default('deploy') }}"
    mode: 0755
    recurse: yes
  with_items: vhosts
  tags: [vhost]

- name: nginx | Create logs directory
  file:
    path: "/srv/www/{{ item.domain }}/logs"
    state: directory
    owner: "{{ item.deploy_username | default('deploy') }}"
    group: "{{ item.deploy_username | default('deploy') }}"
    mode: 0755
    recurse: yes
  with_items: vhosts
  tags: [vhost]

- name: nginx | Push virtualhost configuration
  template:
    src: virtualhost.j2
    dest: "/etc/nginx/sites-available/{{ item.domain }}"
    owner: root
    mode: 0600
    backup: yes
  notify: Reload nginx
  with_items: vhosts
  tags: [vhost]

- name: nginx | Enable virtualhost
  file:
    src: "/etc/nginx/sites-available/{{ item.domain }}"
    dest: "/etc/nginx/sites-enabled/{{ item.domain }}"
    state: link
  notify: Reload nginx
  with_items: vhosts
  tags: [vhost]
