---

- name: PHP | Push pool configuration
  template:
    src: php-pool.conf.j2
    dest: "/etc/php5/fpm/pool.d/{{ item.deploy_username }}.conf"
    owner: root
    mode: 0644
    backup: yes
  with_items: vhosts
  when: item.use_php == true
  notify: Restart PHP
  tags: [vhost]

- name: PHP | Remove pool configuration
  file:
    path: "/etc/php5/fpm/pool.d/{{ item.deploy_username }}.conf"
    state: absent
  with_items: vhosts
  when: item.use_php == false
  notify: Restart PHP
  tags: [vhost]