---

- name: User | Create project deploy user
  user:
    name: "{{ item.deploy_username | default('deploy') }}"
    comment: "Deploy user"
    shell: /bin/bash
    state: present
  with_items: vhosts
  tags: [vhost]

- name: User | Use public keys as authorized keys
  authorized_key:
    user: "{{ item.deploy_username | default('deploy') }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
  with_items: vhosts
  tags: [vhost]