---
- name: Install Postfix
  apt:
    pkg: postfix
    state: present
  tags: [setup,postfix]

- name: Configure Postfix
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: Restart Postfix
  tags: [setup,postfix]

- name: Ensure Postfix is running
  service:
    name: postfix
    state: started
    enabled: yes
  tags: [setup,postfix]
