---
- name: Install Postfix
  apt:
    pkg: postfix
    state: latest
    update_cache: yes
    cache_valid_time: 86400

- name: Configure Postfix
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: Restart Postfix

- name: Ensure Postfix is running
  service:
    name: postfix
    state: started
    enabled: yes