---

- name: Upload dropbox_uploader.sh script to server
  copy:
    src: dropbox_uploader.sh
    dest: /opt/dropbox_uploader.sh
    mode: 0500
    owner: root

- name: Upload configuration file
  template:
    src: ".dropbox_uploader.j2"
    dest: "/root/.dropbox_uploader"
    owner: root
    mode: 0600

- name: Create cron job to perform bi-daily backups
  cron:
    name: "Dropbox backups"
    job: "sh /root/backup.sh >> /var/log/backup.log 2>&1"
    minute: "5"
    hour: "7,19"
    state: present
  when: dropbox_backup_enabled

- name: Disable backups
  cron:
    name: "Dropbox backups"
    state: absent
  when: not dropbox_backup_enabled

- name: Upload backup instructions
  template:
    src: "backup.sh.j2"
    dest: "/root/backup.sh"
    owner: root
    mode: 0600
