---

- name: Restart nginx
  sudo: yes
  service:
    name: nginx
    state: restarted

- name: Start nginx
  sudo: yes
  service:
    name: nginx
    state: started

- name: Reload nginx
  sudo: yes
  service:
    name: nginx
    state: reloaded

- name: Start PHP
  service:
    name: php5-fpm
    state: started

- name: Restart PHP
  service:
    name: php5-fpm
    state: restarted
