---

- name: MySQL | Update the my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: Restart MySQL

- name: Set up cron job to OPTIMIZE databases once a week
  cron:
    name: "OPTIMIZE MySQL tables weekly"
    special_time: weekly
    user: root
    job: "mysqlcheck -o --user=root --password={{ mysql_root_password }} -A"
    cron_file: "mysql"
  tags: [wordpress]