---

- name: Install MySQL
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  with_items:
  - python-mysqldb
  - mysql-server
  - mysql-client
  notify: Start MySQL
  tags: [setup,mysql]