---
- name: Install MySQL
  apt: >
    name={{ item }}
    state=latest
    update_cache=true
    cache_valid_time=3600
  with_items:
  - python-mysqldb
  - mysql-server

- name: Start the MySQL service
  service: >
    name=mysql
    state=started
    enabled=true

- name: Update MySQL root password
  mysql_user: >
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
  with_items:
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost

- name: Push .my.cnf with root credentials
  template: >
    src=.my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    group=root
    mode=0600
    backup=yes

- name: Remove anonymous users from DB
  mysql_user: >
    name=''
    host={{ item }}
    state=absent
  with_items:
  - localhost
  - "{{ ansible_hostname }}"

- name: Remove MySQL test database
  mysql_db: name=test state=absent
