---

- name: Enable
  ufw:
    state: enabled
    policy: deny

- name: Limit connections to SSH port
  ufw:
    rule: limit
    port: "{{ ssh_port }}"

- name: Open HTTP port
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp

- name: Open HTTPS port
  ufw:
    rule: allow
    port: "{{ https_port }}"
    proto: tcp

- name: Open Postfix port
  ufw:
    rule: allow
    port: "{{ postfix_port }}"
    proto: tcp

- name: Open Postfix smtps port
  ufw:
    rule: allow
    port: "{{ smtps_port }}"
    proto: tcp

- name: Open Postfix submission port
  ufw:
    rule: allow
    port: "{{ postfix_submission_port }}"
    proto: tcp
