---

- name: Add PPA
  apt_repository:
    repo: "ppa:duggan/composer"
    update_cache: yes

- name: Install
  apt:
    name: php5-composer
    state: present
    force: yes

- name: Update
  shell: composer self-update
