---

- name: nginx | Create root directory
  file:
    path: "/srv/www/{{ item.site_name }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: web
    mode: 0755
  with_items: wordpress_sites
  tags: [wordpress]

- name: nginx | Create public directories
  file:
    path: "/srv/www/{{ item[0].site_name }}/{{ item[1] }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: web
    mode: 0755
  with_nested:
   - wordpress_sites
   - [ 'current', 'shared', 'releases', 'repo', 'current/web', 'logs' ]
  tags: [wordpress]

- name: Update directory permissions
  file:
    path: "/srv/www/{{ item.site_name }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: web
    mode: 0755
    recurse: yes
  with_items: wordpress_sites
  tags: [wordpress]
