---

- name: Keep temporary old hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1(.*)'
    line: '127.0.1.1{{"\t"}}{{ hostname }}{% if hostname != fqdn %}{{"\t"}}{{ fqdn }}{% endif %}\1'
    state: present
    backup: yes
    backrefs: yes
  when: ansible_hostname != hostname
  tags: [setup,hostname]

- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined and ansible_hostname != hostname
  tags: [setup,hostname]

- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1{{"\t"}}{{ hostname }}{% if hostname != fqdn %}{{"\t"}}{{ fqdn }}{% endif %}'
    state: present
  tags: [setup,hostname]