---

- name: Install general utilities
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - curl
  - build-essential
  - fail2ban
  - language-pack-en
  - git
  - ntp
  - python-software-properties
  - software-properties-common
  - ufw
  - unzip
  - zip
  tags: setup
