---
- name: Timezone | Check current timezone
  shell: cat /etc/timezone
  register: current_timezone
  tags: [setup,timezone]

- name: Timezone | Set the server timezone
  copy:
    content: "{{ timezone }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: current_timezone.stdout != timezone
  notify: Update timezone
  tags: [setup,timezone]