---

- name: Install PHP5-FPM and dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - php5-fpm
  - php5-mysql
  tags: [setup,php]

- name: Disable CGI Fix
  lineinfile:
    dest: /etc/php5/fpm/php.ini
    regexp: "^;?cgi.fix_pathinfo"
    line: "cgi.fix_pathinfo: 0"
    backrefs: yes
    state: present
    backup: yes
  notify: Restart PHP
  tags: [setup,php]

- name: Start the PHP-FPM service
  service:
    name: php5-fpm
    state: started
    enabled: yes
  tags: [setup,php]