---

# See: https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6
- name: Update PPA to use PHP 5.6
  apt_repository:
    repo: ppa:ondrej/php5-5.6
    state: present

- name: Install PHP5-FPM and dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - php5-apcu
    - php5-curl
    - php5-fpm
    - php5-gd
    - php5-imap
    - php5-json
    - php5-mcrypt
    - php5-mysql
    - php5-xmlrpc
    - php5-xsl
  notify: Restart PHP

- name: Configure PHP sensible defaults
  tags: php
  ini_file:
    dest: /etc/php5/fpm/php.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items: php_config_defaults
  when: php_config_defaults|default(False)
  notify: Restart PHP

- name: Configure PHP
  tags: php
  ini_file:
    dest: /etc/php5/fpm/php.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items: php_config
  when: php_config|default(False)
  notify: Restart PHP

- name: Start the PHP-FPM service
  service:
    name: php5-fpm
    state: started
    enabled: yes
